# Site settings
name: blog
email: yunfei614514@gmail.com
author: wangzengfeng
url: https://wyunfei.github.io/
resume_site: http://www.500d.me/cvresume/6274046536/
github: 
baseurl: "/"
description: Actually, less is more!
meta_description: 王增烽;个人博客;
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:categories/:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: wuyunfei

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

